//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_App.Monitoring {
    
    
    public partial class GeocodedClients {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Web_App.BopsWeb Master {
            get {
                return ((Web_App.BopsWeb)(base.Master));
            }
        }
    }
}
