<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_LCID = 1033 %>
<meta http-equiv="Content-Language" content="en-us">
<meta name="GENERATOR" content="Microsoft FrontPage 6.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Active Harbor Projects by Terminal</title>
<meta content="none" name="Microsoft Theme">
<meta content="b" name="Microsoft Border">
</head>

<body><!--msnavigation--><table border="0" cellpadding="0" cellspacing="0" dir="ltr" width="100%"><tr><!--msnavigation--><td valign="top">
<table border="1">
	<caption>Active Harbor Projects by Terminal</caption>
	<thead>
		<tr>
			<th ALIGN="LEFT"><b><font size="1">Origin</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">LFD</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Client</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Vessel</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Product Type</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Destination</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Load Est</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Loads Complete</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Loads Remaining</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Tendered</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Delivered</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">O/S</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Days Remaining</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">LPD Remaining</font></b></th>
		</tr>
	</thead>
	<tbody>
		<!--webbot bot="DatabaseRegionStart" s-columnnames="LFD,Client,Vessel,Origin,Destination,Load Est,Loads Complete,Loads Remaining,Tendered,Delivered,O/S,Days Remaining,LPD Remaining,Days for Calc,Product Type" s-columntypes="135,202,202,202,202,3,3,3,3,3,3,3,5,131,202" s-dataconnection="sdn" b-tableformat="TRUE" b-menuformat="FALSE" s-menuchoice s-menuvalue b-tableborder="TRUE" b-tableexpand="FALSE" b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="5" b-makeform="FALSE" s-recordsource="webHarborDemand" s-displaycolumns="Origin,LFD,Client,Vessel,Product Type,Destination,Load Est,Loads Complete,Loads Remaining,Tendered,Delivered,O/S,Days Remaining,LPD Remaining" s-criteria s-order="[Origin] + [LFD] + [Client] + [Vessel] +" s-sql="SELECT * FROM webHarborDemand ORDER BY Origin ASC,LFD ASC,Client ASC,Vessel ASC" b-procedure="FALSE" clientside suggestedext="asp" s-defaultfields s-norecordsfound="No records returned." i-maxrecords="256" i-groupsize="0" botid="0" u-dblib="_fpclass/fpdblib.inc" u-dbrgn1="_fpclass/fpdbrgn1.inc" u-dbrgn2="_fpclass/fpdbrgn2.inc" tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT * FROM webHarborDemand ORDER BY Origin ASC,LFD ASC,Client ASC,Vessel ASC"
fp_sDefault=""
fp_sNoRecords="<tr><td colspan=14 align=""LEFT"" width=""100%"">No records returned.</td></tr>"
fp_sDataConn="sdn"
fp_iMaxRecords=256
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice=""
fp_sMenuValue=""
fp_sColTypes="&LFD=135&Client=202&Vessel=202&Origin=202&Destination=202&Load Est=3&Loads Complete=3&Loads Remaining=3&Tendered=3&Delivered=3&O/S=3&Days Remaining=3&LPD Remaining=5&Days for Calc=131&Product Type=202&"
fp_iDisplayCols=14
fp_fCustomQuery=False
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="LFD,Client,Vessel,Origin,Destination,Load Est,Loads Complete,Loads Remaining,Tendered,Delivered,O/S,Days Remaining,LPD Remaining,Days for Calc,Product Type" s-column="Origin" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Origin&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Origin")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="LFD,Client,Vessel,Origin,Destination,Load Est,Loads Complete,Loads Remaining,Tendered,Delivered,O/S,Days Remaining,LPD Remaining,Days for Calc,Product Type" s-column="LFD" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;LFD&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"LFD")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="LFD,Client,Vessel,Origin,Destination,Load Est,Loads Complete,Loads Remaining,Tendered,Delivered,O/S,Days Remaining,LPD Remaining,Days for Calc,Product Type" s-column="Client" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Client&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Client")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="LFD,Client,Vessel,Origin,Destination,Load Est,Loads Complete,Loads Remaining,Tendered,Delivered,O/S,Days Remaining,LPD Remaining,Days for Calc,Product Type" s-column="Vessel" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Vessel&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Vessel")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="LFD,Client,Vessel,Origin,Destination,Load Est,Loads Complete,Loads Remaining,Tendered,Delivered,O/S,Days Remaining,LPD Remaining,Days for Calc,Product Type" s-column="Product Type" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Product Type&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Product Type")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="LFD,Client,Vessel,Origin,Destination,Load Est,Loads Complete,Loads Remaining,Tendered,Delivered,O/S,Days Remaining,LPD Remaining,Days for Calc,Product Type" s-column="Destination" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Destination&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Destination")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="LFD,Client,Vessel,Origin,Destination,Load Est,Loads Complete,Loads Remaining,Tendered,Delivered,O/S,Days Remaining,LPD Remaining,Days for Calc,Product Type" s-column="Load Est" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Load Est&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Load Est")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="LFD,Client,Vessel,Origin,Destination,Load Est,Loads Complete,Loads Remaining,Tendered,Delivered,O/S,Days Remaining,LPD Remaining,Days for Calc,Product Type" s-column="Loads Complete" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Loads Complete&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Loads Complete")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="LFD,Client,Vessel,Origin,Destination,Load Est,Loads Complete,Loads Remaining,Tendered,Delivered,O/S,Days Remaining,LPD Remaining,Days for Calc,Product Type" s-column="Loads Remaining" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Loads Remaining&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Loads Remaining")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="LFD,Client,Vessel,Origin,Destination,Load Est,Loads Complete,Loads Remaining,Tendered,Delivered,O/S,Days Remaining,LPD Remaining,Days for Calc,Product Type" s-column="Tendered" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Tendered&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Tendered")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="LFD,Client,Vessel,Origin,Destination,Load Est,Loads Complete,Loads Remaining,Tendered,Delivered,O/S,Days Remaining,LPD Remaining,Days for Calc,Product Type" s-column="Delivered" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Delivered&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Delivered")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="LFD,Client,Vessel,Origin,Destination,Load Est,Loads Complete,Loads Remaining,Tendered,Delivered,O/S,Days Remaining,LPD Remaining,Days for Calc,Product Type" s-column="O/S" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;O/S&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"O/S")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="LFD,Client,Vessel,Origin,Destination,Load Est,Loads Complete,Loads Remaining,Tendered,Delivered,O/S,Days Remaining,LPD Remaining,Days for Calc,Product Type" s-column="Days Remaining" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Days Remaining&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Days Remaining")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="LFD,Client,Vessel,Origin,Destination,Load Est,Loads Complete,Loads Remaining,Tendered,Delivered,O/S,Days Remaining,LPD Remaining,Days for Calc,Product Type" s-column="LPD Remaining" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;LPD Remaining&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"LPD Remaining")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
		</tr>
		<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" b-menuformat="FALSE" u-dbrgn2="_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
</table>

<!--msnavigation--></td></tr><!--msnavigation--></table><!--msnavigation--><table border="0" cellpadding="0" cellspacing="0" width="100%"><tr><td>
<p align="center">

</p>

</td></tr><!--msnavigation--></table></body>

</html>
