<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">

<head>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_LCID = 1033 %>
<meta http-equiv="Content-Language" content="en-us">
<meta name="GENERATOR" content="Microsoft FrontPage 12.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>BOLs without Invoices</title>
<!--mstheme--><link href="_themes/water/wate1011.css" rel="stylesheet" type="text/css"><meta content="water 1011" name="Microsoft Theme">
</head>

<body>

<table border="1">
	<caption>BOLs w/out Invoices</caption>
	<thead>
		<tr>
			<th align="left" class="ms-announcementtitle">Year</th>
			<th align="left" class="ms-announcementtitle">Month</th>
			<th align="left" class="ms-announcementtitle">BOLs w/out Invoice</th>
		</tr>
	</thead>
	<tbody>
		<!--webbot bot="DatabaseRegionStart" s-columnnames="Year,Month,BOLs w/out Invoice" s-columntypes="3,3,3" s-dataconnection="sdn" b-tableformat="TRUE" b-menuformat="FALSE" s-menuchoice="" s-menuvalue="" b-tableborder="TRUE" b-tableexpand="FALSE" b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" b-makeform="FALSE" s-recordsource="webBOLwoutInvoiceCT" s-displaycolumns="Year,Month,BOLs w/out Invoice" s-criteria="" s-order="[Year] - [Month] -" s-sql="SELECT * FROM webBOLwoutInvoiceCT ORDER BY Year DESC,Month DESC" b-procedure="FALSE" clientside="" suggestedext="asp" s-defaultfields="" s-norecordsfound="No records returned." i-maxrecords="256" i-groupsize="0" botid="0" u-dblib="_fpclass/fpdblib.inc" u-dbrgn1="_fpclass/fpdbrgn1.inc" u-dbrgn2="_fpclass/fpdbrgn2.inc" tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=&quot;64&quot; bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdblib.inc"-->
<% if 0 then %>
<script type="text/javascript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</script>
<% end if %>
<%
fp_sQry="SELECT * FROM webBOLwoutInvoiceCT ORDER BY Year DESC,Month DESC"
fp_sDefault=""
fp_sNoRecords="<tr><td colspan=3 align=""left"" width=""100%"">No records returned.</td></tr>"
fp_sDataConn="sdn"
fp_iMaxRecords=256
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice=""
fp_sMenuValue=""
fp_sColTypes="&Year=3&Month=3&BOLs w/out Invoice=3&"
fp_iDisplayCols=3
fp_fCustomQuery=False
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Year,Month,BOLs w/out Invoice" s-column="Year" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside="" b-MenuFormat="" preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Year&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Year")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Year,Month,BOLs w/out Invoice" s-column="Month" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside="" b-MenuFormat="" preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Month&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Month")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Year,Month,BOLs w/out Invoice" s-column="BOLs w/out Invoice" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside="" b-MenuFormat="" preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;BOLs w/out Invoice&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"BOLs w/out Invoice")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
		</tr>
		<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" b-menuformat="FALSE" u-dbrgn2="_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside="" tag="tbody" preview="&lt;tr&gt;&lt;td colspan=&quot;64&quot; bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
</table>

</body>

</html>
