<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">

<head>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_LCID = 1033 %>
<meta http-equiv="Content-Language" content="en-us">
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Budway Phone-based Dwell</title>
</head>

<body>

<p><strong><br>
Fontana Phone Based Dwell</strong></p>
<table border="1">
	<thead>
		<tr>
			<th align="left"><b>Date</b></th>
			<th align="left"><b>Client Name</b></th>
			<th align="left"><b>Dwell</b></th>
			<th align="left"><b>Ct</b></th>
		</tr>
	</thead>
	<tbody>
		<!--webbot bot="DatabaseRegionStart" s-columnnames="Date,Client Name,Client ID,Dwell,Ct" s-columntypes="200,202,3,3,3" s-dataconnection="sdn" b-tableformat="TRUE" b-menuformat="FALSE" s-menuchoice="Date" s-menuvalue="Date" b-tableborder="TRUE" b-tableexpand="FALSE" b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" b-makeform="FALSE" s-recordsource="Agilis Budway Dwell Summary v2" s-displaycolumns="Date,Client Name,Dwell,Ct" s-criteria="" s-order="[Date] -" s-sql="SELECT * FROM &amp;quot;Agilis Budway Dwell Summary v2&amp;quot; ORDER BY Date DESC" b-procedure="FALSE" clientside="" suggestedext="asp" s-defaultfields="" s-norecordsfound="No records returned." i-maxrecords="256" i-groupsize="0" botid="0" u-dblib="_fpclass/fpdblib.inc" u-dbrgn1="_fpclass/fpdbrgn1.inc" u-dbrgn2="_fpclass/fpdbrgn2.inc" tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=&quot;64&quot; bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" b-UseDotNET="FALSE" CurrentExt="" sa-InputTypes="" b-DataGridFormat="FALSE" b-DGridAlternate="TRUE" sa-CritTypes="" b-WasTableFormat="TRUE" startspan --><!--#include file="_fpclass/fpdblib.inc"-->
<% if 0 then %>
<script type="text/javascript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</script>
<% end if %>
<%
fp_sQry="SELECT * FROM ""Agilis Budway Dwell Summary v2"" ORDER BY Date DESC"
fp_sDefault=""
fp_sNoRecords="<tr><td colspan=4 align=""left"" width=""100%"">No records returned.</td></tr>"
fp_sDataConn="sdn"
fp_iMaxRecords=256
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice="Date"
fp_sMenuValue="Date"
fp_sColTypes="&Date=200&Client Name=202&Client ID=3&Dwell=3&Ct=3&"
fp_iDisplayCols=4
fp_fCustomQuery=False
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Date,Client Name,Client ID,Dwell,Ct" s-column="Date" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside="" b-MenuFormat="" preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Date&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Date")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Date,Client Name,Client ID,Dwell,Ct" s-column="Client Name" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside="" b-MenuFormat="" preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Client Name&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Client Name")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Date,Client Name,Client ID,Dwell,Ct" s-column="Dwell" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside="" b-MenuFormat="" preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Dwell&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Dwell")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Date,Client Name,Client ID,Dwell,Ct" s-column="Ct" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside="" b-MenuFormat="" preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Ct&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Ct")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
		</tr>
		<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" b-menuformat="FALSE" u-dbrgn2="_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside="" tag="tbody" preview="&lt;tr&gt;&lt;td colspan=&quot;64&quot; bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
</table>

<p><a href="budway_wait.aspx">Drivers On Clock at Budway</a></p>

<p>&nbsp;</p>

</body>

</html>
