<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_LCID = 1033 %>
<meta http-equiv="Content-Language" content="en-us">
<meta name="GENERATOR" content="Microsoft FrontPage 6.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Day Plan</title>
<meta content="none" name="Microsoft Theme">
<meta content="none, default" name="Microsoft Border">
</head>

<body>

<table border="1">
	<caption>Day Plan</caption>
	<thead>
		<tr>
			<th ALIGN="LEFT"><b><font size="1">Driver</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Plan Date</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Start Time</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Origin</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Load Ref</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Destination</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Arrive</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Depart</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Order</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Load</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">CoilCount</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">COIL</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">WT</font></b></th>
		</tr>
	</thead>
	<tbody>
		<!--webbot bot="DatabaseRegionStart" s-columnnames="Driver,Plan Date,Start Time,Origin,Load Ref,Destination,Arrive,Depart,Order,Load,CoilCount,COIL,WT" s-columntypes="202,135,200,202,202,202,200,200,3,202,5,202,3" s-dataconnection="sdn" b-tableformat="TRUE" b-menuformat="FALSE" s-menuchoice s-menuvalue b-tableborder="TRUE" b-tableexpand="FALSE" b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" b-makeform="FALSE" s-recordsource="rptDriversPlan" s-displaycolumns="Driver,Plan Date,Start Time,Origin,Load Ref,Destination,Arrive,Depart,Order,Load,CoilCount,COIL,WT" s-criteria s-order s-sql="SELECT * FROM rptDriversPlan" b-procedure="FALSE" clientside suggestedext="asp" s-defaultfields s-norecordsfound="No records returned." i-maxrecords="256" i-groupsize="0" botid="0" u-dblib="_fpclass/fpdblib.inc" u-dbrgn1="_fpclass/fpdbrgn1.inc" u-dbrgn2="_fpclass/fpdbrgn2.inc" tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The region will not work unless the page has a file extension of &quot;.asp&quot;. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT * FROM rptDriversPlan"
fp_sDefault=""
fp_sNoRecords="<tr><td colspan=13 align=""LEFT"" width=""100%"">No records returned.</td></tr>"
fp_sDataConn="sdn"
fp_iMaxRecords=256
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice=""
fp_sMenuValue=""
fp_sColTypes="&Driver=202&Plan Date=135&Start Time=200&Origin=202&Load Ref=202&Destination=202&Arrive=200&Depart=200&Order=3&Load=202&CoilCount=5&COIL=202&WT=3&"
fp_iDisplayCols=13
fp_fCustomQuery=False
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Driver,Plan Date,Start Time,Origin,Load Ref,Destination,Arrive,Depart,Order,Load,CoilCount,COIL,WT" s-column="Driver" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Driver&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" s-ColumnTypes="202,135,200,202,202,202,200,200,3,202,5,202,3" startspan --><%=FP_FieldVal(fp_rs,"Driver")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Driver,Plan Date,Start Time,Origin,Load Ref,Destination,Arrive,Depart,Order,Load,CoilCount,COIL,WT" s-column="Plan Date" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Plan Date&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Plan Date")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Driver,Plan Date,Start Time,Origin,Load Ref,Destination,Arrive,Depart,Order,Load,CoilCount,COIL,WT" s-column="Start Time" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Start Time&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Start Time")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Driver,Plan Date,Start Time,Origin,Load Ref,Destination,Arrive,Depart,Order,Load,CoilCount,COIL,WT" s-column="Origin" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Origin&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Origin")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Driver,Plan Date,Start Time,Origin,Load Ref,Destination,Arrive,Depart,Order,Load,CoilCount,COIL,WT" s-column="Load Ref" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Load Ref&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Load Ref")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Driver,Plan Date,Start Time,Origin,Load Ref,Destination,Arrive,Depart,Order,Load,CoilCount,COIL,WT" s-column="Destination" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Destination&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Destination")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Driver,Plan Date,Start Time,Origin,Load Ref,Destination,Arrive,Depart,Order,Load,CoilCount,COIL,WT" s-column="Arrive" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Arrive&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Arrive")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Driver,Plan Date,Start Time,Origin,Load Ref,Destination,Arrive,Depart,Order,Load,CoilCount,COIL,WT" s-column="Depart" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Depart&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Depart")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Driver,Plan Date,Start Time,Origin,Load Ref,Destination,Arrive,Depart,Order,Load,CoilCount,COIL,WT" s-column="Order" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Order&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Order")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Driver,Plan Date,Start Time,Origin,Load Ref,Destination,Arrive,Depart,Order,Load,CoilCount,COIL,WT" s-column="Load" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Load&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Load")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Driver,Plan Date,Start Time,Origin,Load Ref,Destination,Arrive,Depart,Order,Load,CoilCount,COIL,WT" s-column="CoilCount" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;CoilCount&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"CoilCount")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Driver,Plan Date,Start Time,Origin,Load Ref,Destination,Arrive,Depart,Order,Load,CoilCount,COIL,WT" s-column="COIL" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;COIL&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"COIL")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Driver,Plan Date,Start Time,Origin,Load Ref,Destination,Arrive,Depart,Order,Load,CoilCount,COIL,WT" s-column="WT" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;WT&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"WT")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
		</tr>
		<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" b-menuformat="FALSE" u-dbrgn2="_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
</table>

</body>

</html>
