<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_LCID = 1033 %>
<meta http-equiv="Content-Language" content="en-us">
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Detention Detail</title>
</head>

<body>

<form BOTID="0" METHOD="POST" action="detention_detail.asp">
	<input type="hidden" name="fpdbr_0_PagingMove" value="  |&lt;  ">
	<h1>Detention Detail</h1>
	<table BORDER="0">
		<tr>
			<td><b>Filter by Client</b></td>
			<td>
			<input TYPE="TEXT" NAME="Client" VALUE="<%=Server.HtmlEncode(Request("Client"))%>"></td>
		</tr>
	</table>
	<br>
	<input TYPE="Submit"><input TYPE="Reset"><!--webbot bot="SaveAsASP" clientside suggestedext="asp" preview=" " startspan --><!--webbot bot="SaveAsASP" endspan --><p>&nbsp;</p>
</form>
<table border="1">
	<thead>
		<tr>
			<th ALIGN="LEFT"><b>Client</b></th>
			<th ALIGN="LEFT"><b>Plan Date</b></th>
			<th ALIGN="LEFT"><b>Detention</b></th>
			<th ALIGN="LEFT"><b>Arrive Destination</b></th>
		</tr>
	</thead>
	<tbody>
		<!--webbot bot="DatabaseRegionStart" s-columnnames="Client,Plan Date,Detention,Arrive Destination" s-columntypes="202,135,3,135" s-dataconnection="sdn" b-tableformat="TRUE" b-menuformat="FALSE" s-menuchoice="Client" s-menuvalue="Client" b-tableborder="TRUE" b-tableexpand="FALSE" b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" b-makeform="TRUE" s-recordsource="MM Daily Detention for pivot" s-displaycolumns="Client,Plan Date,Detention,Arrive Destination" s-criteria="[Client] CNT {Client} +" s-order="[Plan Date] -" s-sql="SELECT * FROM &amp;quot;MM Daily Detention for pivot&amp;quot; WHERE (Client LIKE '%::Client::%') ORDER BY &amp;quot;Plan Date&amp;quot; DESC" b-procedure="FALSE" clientside suggestedext="asp" s-defaultfields="Client=" s-norecordsfound="No records returned." i-maxrecords="256" i-groupsize="0" botid="0" u-dblib="_fpclass/fpdblib.inc" u-dbrgn1="_fpclass/fpdbrgn1.inc" u-dbrgn2="_fpclass/fpdbrgn2.inc" tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan b-UseDotNET="FALSE" CurrentExt sa-InputTypes="202" b-DataGridFormat="FALSE" b-DGridAlternate="TRUE" sa-CritTypes="202" b-WasTableFormat="TRUE" --><!--#include file="_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT * FROM ""MM Daily Detention for pivot"" WHERE (Client LIKE '%::Client::%') ORDER BY ""Plan Date"" DESC"
fp_sDefault="Client="
fp_sNoRecords="<tr><td colspan=4 align=""LEFT"" width=""100%"">No records returned.</td></tr>"
fp_sDataConn="sdn"
fp_iMaxRecords=256
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice="Client"
fp_sMenuValue="Client"
fp_sColTypes="&Client=202&Plan Date=135&Detention=3&Arrive Destination=135&"
fp_iDisplayCols=4
fp_fCustomQuery=False
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Client,Plan Date,Detention,Arrive Destination" s-column="Client" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Client&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Client")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Client,Plan Date,Detention,Arrive Destination" s-column="Plan Date" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Plan Date&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Plan Date")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Client,Plan Date,Detention,Arrive Destination" s-column="Detention" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Detention&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Detention")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Client,Plan Date,Detention,Arrive Destination" s-column="Arrive Destination" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Arrive Destination&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Arrive Destination")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
		</tr>
		<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" b-menuformat="FALSE" u-dbrgn2="_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
</table>

</body>

</html>
