<HTML>
<HEAD>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html;charset=windows-1252">
<meta http-equiv="refresh" content="120" />
<TITLE>webDispatch Load Sch Performance</TITLE>
</HEAD>
<BODY>
<table width="100%" border="1">
	<thead>
		<tr>
			<th ALIGN="LEFT"><b>Load Date</b></th>
			<th ALIGN="LEFT"><b>Bud Sch Load Ct</b></th>
			<th ALIGN="LEFT"><b>Bud Sch On Time</b></th>
			<th ALIGN="LEFT"><b>Inc Subs On Time</b></th>
			<th ALIGN="LEFT"><b>% Bud Sch On Time</b></th>
			<th ALIGN="LEFT"><b>% 2nd Day Del</b></th>
			<th ALIGN="LEFT"><b><a href="Late%20Loads.asp">Late 2nd Day</a></b></th>
			<th ALIGN="LEFT"><font color="#0000FF"><b>Total Del</b></font></th>
			<th ALIGN="LEFT"><font color="#0000FF"><b>Bud Trk Loads Del</b></font></th>
			<th ALIGN="LEFT"><font color="#0000FF"><b>Driver Ct</b></font></th>
			<th ALIGN="LEFT"><font color="#0000FF"><b>LPD</b></font></th>
		</tr>
	</thead>
	<tbody>
		<!--webbot bot="DatabaseRegionStart" s-columnnames="Load Date,Bud Sch Load Ct,Bud Sch On Time,Inc Subs On Time,% Bud Sch On Time,% 2nd Day Del,Late 2nd Day,Total Del,Bud Trk Loads Del,Driver Ct,LPD" s-columntypes="135,3,202,202,131,131,3,3,3,3,131" s-dataconnection="sdn" b-tableformat="TRUE" b-menuformat="FALSE" s-menuchoice="Load Date" s-menuvalue="Load Date" b-tableborder="TRUE" b-tableexpand="TRUE" b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" b-makeform="FALSE" s-recordsource="vWebLoads Performance Drivers" s-displaycolumns="Load Date,Bud Sch Load Ct,Bud Sch On Time,Inc Subs On Time,% Bud Sch On Time,% 2nd Day Del,Late 2nd Day,Total Del,Bud Trk Loads Del,Driver Ct,LPD" s-criteria s-order="[Load Date] -" s-sql="SELECT * FROM &amp;quot;vWebLoads Performance Drivers&amp;quot; ORDER BY &amp;quot;Load Date&amp;quot; DESC" b-procedure="FALSE" clientside suggestedext="asp" s-defaultfields s-norecordsfound="No records returned." i-maxrecords="256" i-groupsize="15" botid="0" u-dblib="_fpclass/fpdblib.inc" u-dbrgn1="_fpclass/fpdbrgn1.inc" u-dbrgn2="_fpclass/fpdbrgn2.inc" tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" b-UseDotNET="FALSE" CurrentExt sa-InputTypes b-DataGridFormat="FALSE" b-DGridAlternate="TRUE" sa-CritTypes b-WasTableFormat="TRUE" startspan --><!--#include file="_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT * FROM ""vWebLoads Performance Drivers"" ORDER BY ""Load Date"" DESC"
fp_sDefault=""
fp_sNoRecords="<tr><td colspan=11 align=""LEFT"" width=""100%"">No records returned.</td></tr>"
fp_sDataConn="sdn"
fp_iMaxRecords=256
fp_iCommandType=1
fp_iPageSize=15
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice="Load Date"
fp_sMenuValue="Load Date"
fp_sColTypes="&Load Date=135&Bud Sch Load Ct=3&Bud Sch On Time=202&Inc Subs On Time=202&% Bud Sch On Time=131&% 2nd Day Del=131&Late 2nd Day=3&Total Del=3&Bud Trk Loads Del=3&Driver Ct=3&LPD=131&"
fp_iDisplayCols=11
fp_fCustomQuery=False
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Load Date,Bud Sch Load Ct,Bud Sch On Time,Inc Subs On Time,% Bud Sch On Time,% 2nd Day Del,Late 2nd Day,Total Del,Bud Trk Loads Del,Driver Ct,LPD" s-column="Load Date" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Load Date&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Load Date")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Load Date,Bud Sch Load Ct,Bud Sch On Time,Inc Subs On Time,% Bud Sch On Time,% 2nd Day Del,Late 2nd Day,Total Del,Bud Trk Loads Del,Driver Ct,LPD" s-column="Bud Sch Load Ct" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Bud Sch Load Ct&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Bud Sch Load Ct")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Load Date,Bud Sch Load Ct,Bud Sch On Time,Inc Subs On Time,% Bud Sch On Time,% 2nd Day Del,Late 2nd Day,Total Del,Bud Trk Loads Del,Driver Ct,LPD" s-column="Bud Sch On Time" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Bud Sch On Time&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Bud Sch On Time")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Load Date,Bud Sch Load Ct,Bud Sch On Time,Inc Subs On Time,% Bud Sch On Time,% 2nd Day Del,Late 2nd Day,Total Del,Bud Trk Loads Del,Driver Ct,LPD" s-column="Inc Subs On Time" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Inc Subs On Time&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Inc Subs On Time")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Load Date,Bud Sch Load Ct,Bud Sch On Time,Inc Subs On Time,% Bud Sch On Time,% 2nd Day Del,Late 2nd Day,Total Del,Bud Trk Loads Del,Driver Ct,LPD" s-column="% Bud Sch On Time" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;% Bud Sch On Time&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"% Bud Sch On Time")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Load Date,Bud Sch Load Ct,Bud Sch On Time,Inc Subs On Time,% Bud Sch On Time,% 2nd Day Del,Late 2nd Day,Total Del,Bud Trk Loads Del,Driver Ct,LPD" s-column="% 2nd Day Del" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;% 2nd Day Del&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"% 2nd Day Del")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Load Date,Bud Sch Load Ct,Bud Sch On Time,Inc Subs On Time,% Bud Sch On Time,% 2nd Day Del,Late 2nd Day,Total Del,Bud Trk Loads Del,Driver Ct,LPD" s-column="Late 2nd Day" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Late 2nd Day&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Late 2nd Day")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td><font color="#0000FF">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Load Date,Bud Sch Load Ct,Bud Sch On Time,Inc Subs On Time,% Bud Sch On Time,% 2nd Day Del,Late 2nd Day,Total Del,Bud Trk Loads Del,Driver Ct,LPD" s-column="Total Del" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Total Del&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Total Del")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font color="#0000FF">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Load Date,Bud Sch Load Ct,Bud Sch On Time,Inc Subs On Time,% Bud Sch On Time,% 2nd Day Del,Late 2nd Day,Total Del,Bud Trk Loads Del,Driver Ct,LPD" s-column="Bud Trk Loads Del" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Bud Trk Loads Del&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Bud Trk Loads Del")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font color="#0000FF">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Load Date,Bud Sch Load Ct,Bud Sch On Time,Inc Subs On Time,% Bud Sch On Time,% 2nd Day Del,Late 2nd Day,Total Del,Bud Trk Loads Del,Driver Ct,LPD" s-column="Driver Ct" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Driver Ct&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Driver Ct")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font color="#0000FF">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Load Date,Bud Sch Load Ct,Bud Sch On Time,Inc Subs On Time,% Bud Sch On Time,% 2nd Day Del,Late 2nd Day,Total Del,Bud Trk Loads Del,Driver Ct,LPD" s-column="LPD" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;LPD&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"LPD")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
		</tr>
		<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" b-menuformat="FALSE" u-dbrgn2="_fpclass/fpdbrgn2.inc" i-groupsize="15" clientside tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;TR&gt;&lt;TD VALIGN=MIDDLE COLSPAN=64&gt;&lt;NOBR&gt;&lt;INPUT TYPE=Button VALUE=&quot;  |&lt;  &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;   &lt;  &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;  &gt;   &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;  &gt;|  &quot;&gt;  [1/15]&lt;/NOBR&gt;&lt;BR&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
</table>
<h3><font color="#0000FF">Dispatch Performance Definitions</font></h3>
<p><font color="#0000FF">Budway Scheduled Loads - All scheduled loads less will 
call and storage</font></p>
<p><font color="#0000FF">Budway Scheduled On Time - All Budway Scheduled Loads 
delivered on or before their load date.</font></p>
<p><font color="#0000FF">Included Subhaul On Time - Count of subhaul loads 
included in Budway Scheduled On Time</font></p>
<p><font color="#0000FF">% Budway Scheduled On Time - Percentage of Budway 
Scheduled Loads delivered on or before their load date.</font></p>
<p><font color="#0000FF">% 2nd Day Delivered - Percentage of Budway Scheduled 
Loads delivered on or before their load date or the following day.</font></p>
<p><font color="#0000FF">Late 2nd Day - Count of Budway Scheduled Loads pending 
or delivered after load date +1.</font></p>
<p><font color="#0000FF">Total Delivered - All loads delivered regardless of 
load date (no will call, no storage)</font></p>
<p><font color="#0000FF">Budway Truck Loads Delivered - Total count of loads 
delivered on Budway trucks.</font></p>
<p><font color="#0000FF">Driver Count - Count of active drivers.</font></p>
<p><font color="#0000FF">LPD (Loads per Driver) - Budway Truck Loads Delivered / 
Driver Count</font></p>
</BODY>
</HTML>