<HTML>
<HEAD>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html;charset=windows-1252">
<TITLE>Driver Count Report</TITLE>
<base target="rtop">
<!--mstheme--><link href="_themes/budway/budw1011.css" rel="stylesheet" type="text/css"><meta content="budway 1011" name="Microsoft Theme">
</HEAD>
<BODY>
<table border="1">
	<caption><b>Driver Count Report</b></caption>
	<thead>
		<tr>
			<th ALIGN="LEFT"><b><font size="1">Date</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Staff Drivers</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Planned Drivers</font></b></th>
			<th ALIGN="LEFT"><b><font size="1">Active Drivers</font></b></th>
		</tr>
	</thead>
	<tbody>
		<!--webbot bot="DatabaseRegionStart" s-columnnames="LogOutDate,Staff Drivers,Planned Drivers,Active Drivers" s-columntypes="135,3,3,3" s-dataconnection="sdn" b-tableformat="TRUE" b-menuformat="FALSE" s-menuchoice s-menuvalue b-tableborder="TRUE" b-tableexpand="FALSE" b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" b-makeform="FALSE" s-recordsource="webDriverCounts" s-displaycolumns="LogOutDate,Staff Drivers,Planned Drivers,Active Drivers" s-criteria s-order s-sql="SELECT * FROM webDriverCounts" b-procedure="FALSE" clientside suggestedext="asp" s-defaultfields s-norecordsfound="No records returned." i-maxrecords="256" i-groupsize="0" botid="0" u-dblib="_fpclass/fpdblib.inc" u-dbrgn1="_fpclass/fpdbrgn1.inc" u-dbrgn2="_fpclass/fpdbrgn2.inc" tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=&quot;64&quot; bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdblib.inc"-->
<% if 0 then %>
<script type="text/javascript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</script>
<% end if %>
<%
fp_sQry="SELECT * FROM webDriverCounts"
fp_sDefault=""
fp_sNoRecords="<tr><td colspan=4 align=""left"" width=""100%"">No records returned.</td></tr>"
fp_sDataConn="sdn"
fp_iMaxRecords=256
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice=""
fp_sMenuValue=""
fp_sColTypes="&LogOutDate=135&Staff Drivers=3&Planned Drivers=3&Active Drivers=3&"
fp_iDisplayCols=4
fp_fCustomQuery=False
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
			<td>
			<font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="LogOutDate,Staff Drivers,Planned Drivers,Active Drivers" s-column="LogOutDate" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;LogOutDate&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"LogOutDate")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td>
			<font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="LogOutDate,Staff Drivers,Planned Drivers,Active Drivers" s-column="Staff Drivers" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Staff Drivers&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Staff Drivers")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td>
			<font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="LogOutDate,Staff Drivers,Planned Drivers,Active Drivers" s-column="Planned Drivers" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Planned Drivers&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Planned Drivers")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td>
			<font size="1">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="LogOutDate,Staff Drivers,Planned Drivers,Active Drivers" s-column="Active Drivers" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Active Drivers&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Active Drivers")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
		</tr>
		<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" b-menuformat="FALSE" u-dbrgn2="_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=&quot;64&quot; bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
</table>
<font size="1">
</font>
<p><a target="left2" href="drivers_not_assigned.asp">Drivers Not Assigned</a></p>
<p>Service/Shop/Xfer excluded.</p>
</BODY>
</HTML>