<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Excess Detention 15 day x top 30</title>
</head>

<body>

<p>
<object classid="clsid:0002E55D-0000-0000-C000-000000000046" id="ChartSpace2">
	<param name="XMLData" value="&lt;xml xmlns:x=&quot;urn:schemas-microsoft-com:office:excel&quot;&gt;
 &lt;x:ChartSpace&gt;
  &lt;x:OWCVersion&gt;11.0.0.6555         &lt;/x:OWCVersion&gt;
  &lt;x:Width&gt;15240&lt;/x:Width&gt;
  &lt;x:Height&gt;10160&lt;/x:Height&gt;
  &lt;x:DataSource&gt;
   &lt;x:Type&gt;InternalPivotList&lt;/x:Type&gt;
   &lt;x:PivotListXML&gt;&amp;lt;xml xmlns:x=&amp;quot;urn:schemas-microsoft-com:office:excel&amp;quot;&amp;gt;&amp;#13;&amp;#10; &amp;lt;x:PivotTable&amp;gt;&amp;#13;&amp;#10;  &amp;lt;x:OWCVersion&amp;gt;11.0.0.6555         &amp;lt;/x:OWCVersion&amp;gt;&amp;#13;&amp;#10;  &amp;lt;x:DisplayScreenTips/&amp;gt;&amp;#13;&amp;#10;  &amp;lt;x:CubeProvider&amp;gt;msolap.2&amp;lt;/x:CubeProvider&amp;gt;&amp;#13;&amp;#10;  &amp;lt;x:CacheDetails/&amp;gt;&amp;#13;&amp;#10;  &amp;lt;x:ConnectionString&amp;gt;Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=True;Initial Catalog=DWS No Rep Data;Data Source=sql1;Use Procedure for Prepare=1;Auto Translate=True;Packet Size=4096;Workstation ID=ENPOWERP4HT;Use Encryption for Data=False;Tag with column collation when possible=False&amp;lt;/x:ConnectionString&amp;gt;&amp;#13;&amp;#10;  &amp;lt;x:DataMember&amp;gt;dbo.Detention Excess 15/30 for pivot&amp;lt;/x:DataMember&amp;gt;&amp;#13;&amp;#10;  &amp;lt;x:Name&amp;gt;Microsoft Office PivotTable 11.0&amp;lt;/x:Name&amp;gt;&amp;#13;&amp;#10;  &amp;lt;x:PivotField&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:Name&amp;gt;Client&amp;lt;/x:Name&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:Orientation&amp;gt;Row&amp;lt;/x:Orientation&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:EncodedType&amp;gt;adVarWChar&amp;lt;/x:EncodedType&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:CompareOrderedMembersBy&amp;gt;UniqueName&amp;lt;/x:CompareOrderedMembersBy&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:AutoSortOrder&amp;gt;Ascending&amp;lt;/x:AutoSortOrder&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:AutoSortField&amp;gt;Sum of Detention&amp;lt;/x:AutoSortField&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:Expanded/&amp;gt;&amp;#13;&amp;#10;  &amp;lt;/x:PivotField&amp;gt;&amp;#13;&amp;#10;  &amp;lt;x:PivotField&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:Name&amp;gt;Week&amp;lt;/x:Name&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:DataType&amp;gt;Integer&amp;lt;/x:DataType&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:EncodedType&amp;gt;adInteger&amp;lt;/x:EncodedType&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:CompareOrderedMembersBy&amp;gt;UniqueName&amp;lt;/x:CompareOrderedMembersBy&amp;gt;&amp;#13;&amp;#10;  &amp;lt;/x:PivotField&amp;gt;&amp;#13;&amp;#10;  &amp;lt;x:PivotField&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:Name&amp;gt;Detention&amp;lt;/x:Name&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:DataType&amp;gt;Integer&amp;lt;/x:DataType&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:PLDataOrientation/&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:EncodedType&amp;gt;adInteger&amp;lt;/x:EncodedType&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:CompareOrderedMembersBy&amp;gt;UniqueName&amp;lt;/x:CompareOrderedMembersBy&amp;gt;&amp;#13;&amp;#10;  &amp;lt;/x:PivotField&amp;gt;&amp;#13;&amp;#10;  &amp;lt;x:PivotField&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:Name&amp;gt;Data&amp;lt;/x:Name&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:Orientation&amp;gt;Column&amp;lt;/x:Orientation&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:Position&amp;gt;-1&amp;lt;/x:Position&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:DataField/&amp;gt;&amp;#13;&amp;#10;  &amp;lt;/x:PivotField&amp;gt;&amp;#13;&amp;#10;  &amp;lt;x:PivotField&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:Name&amp;gt;Sum of Detention&amp;lt;/x:Name&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:PLName&amp;gt;Total1&amp;lt;/x:PLName&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:TotalNumber&amp;gt;0&amp;lt;/x:TotalNumber&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:Orientation&amp;gt;Data&amp;lt;/x:Orientation&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:Position&amp;gt;1&amp;lt;/x:Position&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:ParentField&amp;gt;Detention&amp;lt;/x:ParentField&amp;gt;&amp;#13;&amp;#10;  &amp;lt;/x:PivotField&amp;gt;&amp;#13;&amp;#10;  &amp;lt;x:PivotData&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:Top&amp;gt;0.0&amp;lt;/x:Top&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:TopOffset&amp;gt;0&amp;lt;/x:TopOffset&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:Left&amp;gt;0&amp;lt;/x:Left&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:LeftOffset&amp;gt;0&amp;lt;/x:LeftOffset&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:SeqNum&amp;gt;156&amp;lt;/x:SeqNum&amp;gt;&amp;#13;&amp;#10;  &amp;lt;/x:PivotData&amp;gt;&amp;#13;&amp;#10;  &amp;lt;x:PivotView&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:IsNotFiltered/&amp;gt;&amp;#13;&amp;#10;   &amp;lt;x:DetailSortOrder&amp;gt;Client&amp;lt;/x:DetailSortOrder&amp;gt;&amp;#13;&amp;#10;  &amp;lt;/x:PivotView&amp;gt;&amp;#13;&amp;#10; &amp;lt;/x:PivotTable&amp;gt;&amp;#13;&amp;#10;&amp;lt;/xml&amp;gt;&lt;/x:PivotListXML&gt;
  &lt;/x:DataSource&gt;
  &lt;x:BoundSeries&gt;
   &lt;x:DataSourceIndex&gt;0&lt;/x:DataSourceIndex&gt;
  &lt;/x:BoundSeries&gt;
  &lt;x:Category&gt;
   &lt;x:DataSourceIndex&gt;0&lt;/x:DataSourceIndex&gt;
  &lt;/x:Category&gt;
  &lt;x:Value&gt;
   &lt;x:DataSourceIndex&gt;0&lt;/x:DataSourceIndex&gt;
   &lt;x:Data&gt;Total1&lt;/x:Data&gt;
  &lt;/x:Value&gt;
  &lt;x:BoundCharts&gt;
   &lt;x:DataSourceIndex&gt;0&lt;/x:DataSourceIndex&gt;
  &lt;/x:BoundCharts&gt;
  &lt;x:FormatValue&gt;
   &lt;x:DataSourceIndex&gt;-3&lt;/x:DataSourceIndex&gt;
   &lt;x:Data&gt;2&lt;/x:Data&gt;
  &lt;/x:FormatValue&gt;
  &lt;x:PivotAggOrientation&gt;None&lt;/x:PivotAggOrientation&gt;
  &lt;x:HidePivotFields/&gt;
  &lt;x:Palette&gt;
   &lt;x:Entry&gt;#000000&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#000000&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#000000&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#000000&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#000000&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#000000&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#000000&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#000000&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#000000&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#000000&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#000000&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#000000&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#000000&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#000000&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#000000&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#000000&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#8080FF&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#802060&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#FFFFA0&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#A0E0E0&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#600080&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#FF8080&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#008080&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#C0C0FF&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#000080&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#FF00FF&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#80FFFF&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#0080FF&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#FF8080&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#C0FF80&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#FFC0FF&lt;/x:Entry&gt;
   &lt;x:Entry&gt;#FF80FF&lt;/x:Entry&gt;
  &lt;/x:Palette&gt;
  &lt;x:DefaultFont&gt;Arial&lt;/x:DefaultFont&gt;
  &lt;x:Chart&gt;
   &lt;x:PlotArea&gt;
    &lt;x:Graph&gt;
     &lt;x:SubType&gt;Clustered&lt;/x:SubType&gt;
     &lt;x:Type&gt;Bar&lt;/x:Type&gt;
     &lt;x:Series&gt;
      &lt;x:FormatMap&gt;
      &lt;/x:FormatMap&gt;
      &lt;x:Name&gt;Series&lt;/x:Name&gt;
      &lt;x:Caption&gt;
       &lt;x:DataSourceIndex&gt;-1&lt;/x:DataSourceIndex&gt;
       &lt;x:Data&gt;&amp;quot;Series&amp;quot;&lt;/x:Data&gt;
      &lt;/x:Caption&gt;
      &lt;x:Index&gt;0&lt;/x:Index&gt;
      &lt;x:Category&gt;
       &lt;x:DataSourceIndex&gt;0&lt;/x:DataSourceIndex&gt;
      &lt;/x:Category&gt;
      &lt;x:Value&gt;
       &lt;x:DataSourceIndex&gt;0&lt;/x:DataSourceIndex&gt;
       &lt;x:Data&gt;Total1&lt;/x:Data&gt;
      &lt;/x:Value&gt;
      &lt;x:FormatValue&gt;
       &lt;x:DataSourceIndex&gt;-3&lt;/x:DataSourceIndex&gt;
       &lt;x:Data&gt;2&lt;/x:Data&gt;
      &lt;/x:FormatValue&gt;
      &lt;x:Marker&gt;
       &lt;x:Symbol&gt;None&lt;/x:Symbol&gt;
      &lt;/x:Marker&gt;
      &lt;x:Explode&gt;0&lt;/x:Explode&gt;
      &lt;x:Thickness&gt;10&lt;/x:Thickness&gt;
      &lt;x:DataSourceIndex&gt;0&lt;/x:DataSourceIndex&gt;
      &lt;x:Identifier&gt;!&lt;/x:Identifier&gt;
     &lt;/x:Series&gt;
     &lt;x:Dimension&gt;
      &lt;x:ScaleID&gt;453057728&lt;/x:ScaleID&gt;
      &lt;x:Index&gt;Categories&lt;/x:Index&gt;
     &lt;/x:Dimension&gt;
     &lt;x:Dimension&gt;
      &lt;x:ScaleID&gt;453056560&lt;/x:ScaleID&gt;
      &lt;x:Index&gt;Value&lt;/x:Index&gt;
     &lt;/x:Dimension&gt;
     &lt;x:Dimension&gt;
      &lt;x:ScaleID&gt;453110200&lt;/x:ScaleID&gt;
      &lt;x:Index&gt;FormatValue&lt;/x:Index&gt;
     &lt;/x:Dimension&gt;
     &lt;x:Overlap&gt;0&lt;/x:Overlap&gt;
     &lt;x:GapWidth&gt;150&lt;/x:GapWidth&gt;
     &lt;x:FirstSliceAngle&gt;0&lt;/x:FirstSliceAngle&gt;
    &lt;/x:Graph&gt;
    &lt;x:Axis&gt;
     &lt;x:AxisID&gt;453063484&lt;/x:AxisID&gt;
     &lt;x:ScaleID&gt;453057728&lt;/x:ScaleID&gt;
     &lt;x:Type&gt;Category&lt;/x:Type&gt;
     &lt;x:MajorTick&gt;Outside&lt;/x:MajorTick&gt;
     &lt;x:MinorTick&gt;None&lt;/x:MinorTick&gt;
     &lt;x:Placement&gt;Left&lt;/x:Placement&gt;
     &lt;x:GroupingEnum&gt;Auto&lt;/x:GroupingEnum&gt;
    &lt;/x:Axis&gt;
    &lt;x:Axis&gt;
     &lt;x:AxisID&gt;267141108&lt;/x:AxisID&gt;
     &lt;x:ScaleID&gt;453056560&lt;/x:ScaleID&gt;
     &lt;x:Type&gt;Value&lt;/x:Type&gt;
     &lt;x:Number&gt;
      &lt;x:FormatString&gt;General&lt;/x:FormatString&gt;
     &lt;/x:Number&gt;
     &lt;x:MajorGridlines&gt;
     &lt;/x:MajorGridlines&gt;
     &lt;x:MajorTick&gt;Outside&lt;/x:MajorTick&gt;
     &lt;x:MinorTick&gt;None&lt;/x:MinorTick&gt;
     &lt;x:Placement&gt;Bottom&lt;/x:Placement&gt;
    &lt;/x:Axis&gt;
   &lt;/x:PlotArea&gt;
   &lt;x:Identifier&gt;&lt;/x:Identifier&gt;
  &lt;/x:Chart&gt;
  &lt;x:Scaling&gt;
   &lt;x:ScaleID&gt;453057728&lt;/x:ScaleID&gt;
  &lt;/x:Scaling&gt;
  &lt;x:Scaling&gt;
   &lt;x:ScaleID&gt;453056560&lt;/x:ScaleID&gt;
  &lt;/x:Scaling&gt;
  &lt;x:Scaling&gt;
   &lt;x:ScaleID&gt;453110200&lt;/x:ScaleID&gt;
  &lt;/x:Scaling&gt;
  &lt;x:DisplayToolbar/&gt;
 &lt;/x:ChartSpace&gt;
&lt;/xml&gt;">
	<param name="ScreenUpdating" value="-1">
	<param name="EnableEvents" value="-1">
	<table width='100%' cellpadding='0' cellspacing='0' border='0' height='8'><tr><td bgColor='#336699' height='25' width='10%'>&nbsp;</td><td bgColor='#666666'width='85%'><font face='Tahoma' color='white' size='4'><b>&nbsp; Missing: Microsoft Office Web Components</b></font></td></tr><tr><td bgColor='#cccccc' width='15'>&nbsp;</td><td bgColor='#cccccc' width='500px'><br> <font face='Tahoma' size='2'>This page requires the Microsoft Office Web Components.<p align='center'> <a href='E:/files/owc11/setup.exe'>Click here to install Microsoft Office Web Components.</a>.</p></font><p><font face='Tahoma' size='2'>This page also requires Microsoft Internet Explorer 5.01 or higher.</p><p align='center'><a href='http://www.microsoft.com/windows/ie/default.htm'> Click here to install the latest Internet Explorer</a>.</font><br>&nbsp;</td></tr></table></object>
</p>
<p><a href="excess_detention_15_day_x_top_30.asp">Data</a></p>

</body>

</html>
