<HTML>
<HEAD>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=windows-1252">
<TITLE>Planned Loads Summary</TITLE>
<base target="rbottom">
<!--mstheme--><link href="_themes/budway/budw1011.css" rel="stylesheet" type="text/css"><meta content="budway 1011" name="Microsoft Theme">
</HEAD>
<BODY>
<div align="center">
<table border="1">
	<caption><b>Planner Summary</b></caption>
	<thead>
		<tr>
			<th ALIGN="LEFT" bgcolor="#808080"><b>
			<font size="1" face="Arial" color="#000000">Plan Date</font></b></th>
			<th ALIGN="LEFT" bgcolor="#808080"><b>
			<font size="1" face="Arial" color="#000000">Ct Planned</font></b></th>
			<th ALIGN="LEFT" bgcolor="#808080"><b>
			<font size="1" face="Arial" color="#000000">Tendered</font></b></th>
			<th ALIGN="LEFT" bgcolor="#808080"><b>
			<font size="1" face="Arial" color="#000000">Unplanned Roll Over</font></b></th>
			<th ALIGN="LEFT" bgcolor="#808080"><b>
			<font size="1" face="Arial" color="#000000">Delivered</font></b></th>
		</tr>
	</thead>
	<tbody>
		<!--webbot bot="DatabaseRegionStart" s-columnnames="Plan Date,Ct Planned,Tendered,Unplanned Roll Over,Delivered" s-columntypes="135,3,3,3,3" s-dataconnection="sdn" b-tableformat="TRUE" b-menuformat="FALSE" s-menuchoice="Plan Date" s-menuvalue="Plan Date" b-tableborder="TRUE" b-tableexpand="FALSE" b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" b-makeform="FALSE" s-recordsource="Planner Ct Planned" s-displaycolumns="Plan Date,Ct Planned,Tendered,Unplanned Roll Over,Delivered" s-criteria s-order="[Plan Date] -" s-sql="SELECT * FROM &amp;quot;Planner Ct Planned&amp;quot; ORDER BY &amp;quot;Plan Date&amp;quot; DESC" b-procedure="FALSE" clientside suggestedext="asp" s-defaultfields s-norecordsfound="No records returned." i-maxrecords="256" i-groupsize="0" botid="0" u-dblib="_fpclass/fpdblib.inc" u-dbrgn1="_fpclass/fpdbrgn1.inc" u-dbrgn2="_fpclass/fpdbrgn2.inc" tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan b-UseDotNET="FALSE" CurrentExt sa-InputTypes b-DataGridFormat="FALSE" b-DGridAlternate="TRUE" sa-CritTypes b-WasTableFormat="TRUE" --><!--#include file="_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT * FROM ""Planner Ct Planned"" ORDER BY ""Plan Date"" DESC"
fp_sDefault=""
fp_sNoRecords="<tr><td colspan=5 align=""LEFT"" width=""100%"">No records returned.</td></tr>"
fp_sDataConn="sdn"
fp_iMaxRecords=256
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice="Plan Date"
fp_sMenuValue="Plan Date"
fp_sColTypes="&Plan Date=135&Ct Planned=3&Tendered=3&Unplanned Roll Over=3&Delivered=3&"
fp_iDisplayCols=5
fp_fCustomQuery=False
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
			<td><font size="1" face="Arial">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Plan Date,Ct Planned,Tendered,Unplanned Roll Over,Delivered" s-column="Plan Date" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Plan Date&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Plan Date")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1" face="Arial">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Plan Date,Ct Planned,Tendered,Unplanned Roll Over,Delivered" s-column="Ct Planned" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Ct Planned&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Ct Planned")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1" face="Arial">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Plan Date,Ct Planned,Tendered,Unplanned Roll Over,Delivered" s-column="Tendered" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Tendered&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Tendered")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1" face="Arial">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Plan Date,Ct Planned,Tendered,Unplanned Roll Over,Delivered" s-column="Unplanned Roll Over" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Unplanned Roll Over&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Unplanned Roll Over")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="1" face="Arial">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Plan Date,Ct Planned,Tendered,Unplanned Roll Over,Delivered" s-column="Delivered" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Delivered&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Delivered")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
		</tr>
		<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" b-menuformat="FALSE" u-dbrgn2="_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
</table>
</div>
<p>Main Menu: <a href="dispatch_reports.htm">Fontana Dispatch Reports</a></p>
</BODY>
</HTML>