<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_LCID = 1033 %>
<meta http-equiv="Content-Language" content="en-us">
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Solution Sample</title>
</head>

<body>

<form BOTID="0" METHOD="POST" action="solution_sample.asp">
	<input type="hidden" name="fpdbr_0_PagingMove" value="  |&lt;  ">
	<h1>Solution Sample</h1>
	<table BORDER="0">
		<tr>
			<td><b>Date (format with 8 digits e.g. 07/11/2007):</b></td>
			<td>
			<input TYPE="TEXT" NAME="Date" VALUE="<%=Server.HtmlEncode(Request("Date"))%>"></td>
		</tr>
	</table>
	<br>
	<input TYPE="Submit"><input TYPE="Reset"><!--webbot bot="SaveAsASP" clientside suggestedext="asp" preview=" " startspan --><!--webbot bot="SaveAsASP" endspan --><p>
	<a href="demand_sample.asp">Demand Sample</a></p>
</form>
<table border="1">
	<thead>
		<tr>
			<th ALIGN="LEFT"><b>Date</b></th>
			<th ALIGN="LEFT"><b>Driver Ref</b></th>
			<th ALIGN="LEFT"><b>Order</b></th>
			<th ALIGN="LEFT"><b>Origin Ref</b></th>
			<th ALIGN="LEFT"><b>Origin</b></th>
			<th ALIGN="LEFT"><b>Destination Ref</b></th>
			<th ALIGN="LEFT"><b>Destination</b></th>
			<th ALIGN="LEFT"><b>Destination Detention</b></th>
			<th ALIGN="LEFT"><b>Transit</b></th>
		</tr>
	</thead>
	<tbody>
		<!--webbot bot="DatabaseRegionStart" s-columnnames="Date,Driver Ref,Order,Origin Ref,Origin,Origin Detention,Destination Ref,Destination,Destination Detention,Transit" s-columntypes="200,3,3,3,202,3,3,202,3,3" s-dataconnection="sdn" b-tableformat="TRUE" b-menuformat="FALSE" s-menuchoice s-menuvalue b-tableborder="TRUE" b-tableexpand="FALSE" b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" b-makeform="TRUE" s-recordsource="OR dispatch solution" s-displaycolumns="Date,Driver Ref,Order,Origin Ref,Origin,Destination Ref,Destination,Destination Detention,Transit" s-criteria="[Date] EQ {Date} +" s-order s-sql="SELECT * FROM &quot;OR dispatch solution&quot; WHERE (Date =  '::Date::')" b-procedure="FALSE" clientside suggestedext="asp" s-defaultfields="Date=" s-norecordsfound="No records returned." i-maxrecords="0" i-groupsize="0" botid="0" u-dblib="_fpclass/fpdblib.inc" u-dbrgn1="_fpclass/fpdbrgn1.inc" u-dbrgn2="_fpclass/fpdbrgn2.inc" tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT * FROM ""OR dispatch solution"" WHERE (Date =  '::Date::')"
fp_sDefault="Date="
fp_sNoRecords="<tr><td colspan=9 align=""LEFT"" width=""100%"">No records returned.</td></tr>"
fp_sDataConn="sdn"
fp_iMaxRecords=0
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice=""
fp_sMenuValue=""
fp_sColTypes="&Date=200&Driver Ref=3&Order=3&Origin Ref=3&Origin=202&Origin Detention=3&Destination Ref=3&Destination=202&Destination Detention=3&Transit=3&"
fp_iDisplayCols=9
fp_fCustomQuery=False
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Date,Driver Ref,Order,Origin Ref,Origin,Origin Detention,Destination Ref,Destination,Destination Detention,Transit" s-column="Date" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Date&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Date")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Date,Driver Ref,Order,Origin Ref,Origin,Origin Detention,Destination Ref,Destination,Destination Detention,Transit" s-column="Driver Ref" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Driver Ref&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Driver Ref")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Date,Driver Ref,Order,Origin Ref,Origin,Origin Detention,Destination Ref,Destination,Destination Detention,Transit" s-column="Order" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Order&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Order")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Date,Driver Ref,Order,Origin Ref,Origin,Origin Detention,Destination Ref,Destination,Destination Detention,Transit" s-column="Origin Ref" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Origin Ref&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Origin Ref")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Date,Driver Ref,Order,Origin Ref,Origin,Origin Detention,Destination Ref,Destination,Destination Detention,Transit" s-column="Origin" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Origin&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Origin")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Date,Driver Ref,Order,Origin Ref,Origin,Origin Detention,Destination Ref,Destination,Destination Detention,Transit" s-column="Destination Ref" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Destination Ref&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Destination Ref")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Date,Driver Ref,Order,Origin Ref,Origin,Origin Detention,Destination Ref,Destination,Destination Detention,Transit" s-column="Destination" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Destination&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Destination")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Date,Driver Ref,Order,Origin Ref,Origin,Origin Detention,Destination Ref,Destination,Destination Detention,Transit" s-column="Destination Detention" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Destination Detention&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Destination Detention")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Date,Driver Ref,Order,Origin Ref,Origin,Origin Detention,Destination Ref,Destination,Destination Detention,Transit" s-column="Transit" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Transit&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Transit")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
		</tr>
		<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" b-menuformat="FALSE" u-dbrgn2="_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
</table>

</body>

</html>
