<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_LCID = 1033 %>
<meta http-equiv="Content-Language" content="en-us">
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Harbor Plan Summary</title>
</head>

<body>

<table border="1">
	<caption><b>Today's Harbor Plan Summary</b></caption>
	<thead>
		<tr>
			<th ALIGN="LEFT"><b><font size="2">Request Date</font></b></th>
			<th ALIGN="LEFT"><b><font size="2">Plan Date</font></b></th>
			<th ALIGN="LEFT"><b><font size="2">Vessel</font></b></th>
			<th ALIGN="LEFT"><b><font size="2">Origin</font></b></th>
			<th ALIGN="LEFT"><b><font size="2">Shipper</font></b></th>
			<th ALIGN="LEFT"><b><font size="2">Destination</font></b></th>
			<th ALIGN="LEFT"><b><font size="2">Loads Requested</font></b></th>
			<th ALIGN="LEFT"><b><font size="2">Loads Planned</font></b></th>
		</tr>
	</thead>
	<tbody>
		<!--webbot bot="DatabaseRegionStart" s-columnnames="Request Date,Plan Date,Vessel,Origin,Shipper,Destination,Loads Requested,Loads Planned" s-columntypes="135,135,202,202,202,202,3,3" s-dataconnection="sdn" b-tableformat="TRUE" b-menuformat="FALSE" s-menuchoice="Request Date" s-menuvalue="Request Date" b-tableborder="TRUE" b-tableexpand="FALSE" b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" b-makeform="FALSE" s-recordsource="Harbor Planned Load Summary" s-displaycolumns="Request Date,Plan Date,Vessel,Origin,Shipper,Destination,Loads Requested,Loads Planned" s-criteria s-order="[Origin] + [Vessel] + [Shipper] + [Destination] +" s-sql="SELECT * FROM &amp;quot;Harbor Planned Load Summary&amp;quot; ORDER BY Origin ASC,Vessel ASC,Shipper ASC,Destination ASC" b-procedure="FALSE" clientside suggestedext="asp" s-defaultfields s-norecordsfound="No records returned." i-maxrecords="256" i-groupsize="0" botid="0" u-dblib="_fpclass/fpdblib.inc" u-dbrgn1="_fpclass/fpdbrgn1.inc" u-dbrgn2="_fpclass/fpdbrgn2.inc" tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" b-UseDotNET="FALSE" CurrentExt sa-InputTypes b-DataGridFormat="FALSE" b-DGridAlternate="TRUE" sa-CritTypes b-WasTableFormat="TRUE" startspan --><!--#include file="_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT * FROM ""Harbor Planned Load Summary"" ORDER BY Origin ASC,Vessel ASC,Shipper ASC,Destination ASC"
fp_sDefault=""
fp_sNoRecords="<tr><td colspan=8 align=""LEFT"" width=""100%"">No records returned.</td></tr>"
fp_sDataConn="sdn"
fp_iMaxRecords=256
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice="Request Date"
fp_sMenuValue="Request Date"
fp_sColTypes="&Request Date=135&Plan Date=135&Vessel=202&Origin=202&Shipper=202&Destination=202&Loads Requested=3&Loads Planned=3&"
fp_iDisplayCols=8
fp_fCustomQuery=False
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
			<td><font size="2">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Request Date,Plan Date,Vessel,Origin,Shipper,Destination,Loads Requested,Loads Planned" s-column="Request Date" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Request Date&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Request Date")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="2">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Request Date,Plan Date,Vessel,Origin,Shipper,Destination,Loads Requested,Loads Planned" s-column="Plan Date" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Plan Date&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Plan Date")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="2">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Request Date,Plan Date,Vessel,Origin,Shipper,Destination,Loads Requested,Loads Planned" s-column="Vessel" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Vessel&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Vessel")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="2">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Request Date,Plan Date,Vessel,Origin,Shipper,Destination,Loads Requested,Loads Planned" s-column="Origin" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Origin&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Origin")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="2">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Request Date,Plan Date,Vessel,Origin,Shipper,Destination,Loads Requested,Loads Planned" s-column="Shipper" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Shipper&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Shipper")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="2">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Request Date,Plan Date,Vessel,Origin,Shipper,Destination,Loads Requested,Loads Planned" s-column="Destination" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Destination&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Destination")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="2">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Request Date,Plan Date,Vessel,Origin,Shipper,Destination,Loads Requested,Loads Planned" s-column="Loads Requested" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Loads Requested&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Loads Requested")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
			<td><font size="2">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Request Date,Plan Date,Vessel,Origin,Shipper,Destination,Loads Requested,Loads Planned" s-column="Loads Planned" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Loads Planned&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Loads Planned")%><!--webbot bot="DatabaseResultColumn" endspan --></font></td>
		</tr>
		<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" b-menuformat="FALSE" u-dbrgn2="_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
</table>

</body>

</html>
