<HTML>
<HEAD>
<% ' FP_ASP -- ASP Automatically generated by a FrontPage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html;charset=windows-1252">
<TITLE>UPI Status Summary</TITLE>
<base target="rbottom">
<!--mstheme--><link href="_themes/budway/budw1011.css" rel="stylesheet" type="text/css"><meta content="budway 1011" name="Microsoft Theme">
</HEAD>
<BODY>
<table border="1">
	<caption><b>UPI MTD Status</b></caption>
	<thead>
		<tr>
			<th ALIGN="LEFT"><b>Client</b></th>
			<th ALIGN="LEFT"><b>month</b></th>
			<th ALIGN="LEFT"><b>year</b></th>
			<th ALIGN="LEFT"><b>MTD Load Count</b></th>
			<th ALIGN="LEFT"><b>MTD Tons</b></th>
			<th ALIGN="LEFT"><b>UPI Loads Delivered Today</b></th>
			<th ALIGN="LEFT"><b>UPI Loads Remaining Today</b></th>
		</tr>
	</thead>
	<tbody>
		<!--webbot bot="DatabaseRegionStart" s-columnnames="Client,month,year,MTD Load Count,MTD Tons,UPI Loads Delivered Today,UPI Loads Remaining Today" s-columntypes="202,3,3,3,5,3,3" s-dataconnection="sdn" b-tableformat="TRUE" b-menuformat="FALSE" s-menuchoice s-menuvalue b-tableborder="TRUE" b-tableexpand="FALSE" b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-listformat="0" b-makeform="FALSE" s-recordsource="UPI Status" s-displaycolumns="Client,month,year,MTD Load Count,MTD Tons,UPI Loads Delivered Today,UPI Loads Remaining Today" s-criteria s-order s-sql="SELECT * FROM &quot;UPI Status&quot;" b-procedure="FALSE" clientside suggestedext="asp" s-defaultfields s-norecordsfound="No records returned." i-maxrecords="256" i-groupsize="0" botid="0" u-dblib="_fpclass/fpdblib.inc" u-dbrgn1="_fpclass/fpdbrgn1.inc" u-dbrgn2="_fpclass/fpdbrgn2.inc" tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=&quot;64&quot; bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region. The page must be fetched from a web server with a web browser to display correctly; the current web is stored on your local disk or network.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdblib.inc"-->
<% if 0 then %>
<script type="text/javascript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</script>
<% end if %>
<%
fp_sQry="SELECT * FROM ""UPI Status"""
fp_sDefault=""
fp_sNoRecords="<tr><td colspan=7 align=""left"" width=""100%"">No records returned.</td></tr>"
fp_sDataConn="sdn"
fp_iMaxRecords=256
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice=""
fp_sMenuValue=""
fp_sColTypes="&Client=202&month=3&year=3&MTD Load Count=3&MTD Tons=5&UPI Loads Delivered Today=3&UPI Loads Remaining Today=3&"
fp_iDisplayCols=7
fp_fCustomQuery=False
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan --><tr>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Client,month,year,MTD Load Count,MTD Tons,UPI Loads Delivered Today,UPI Loads Remaining Today" s-column="Client" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Client&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"Client")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Client,month,year,MTD Load Count,MTD Tons,UPI Loads Delivered Today,UPI Loads Remaining Today" s-column="month" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;month&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"month")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td>
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Client,month,year,MTD Load Count,MTD Tons,UPI Loads Delivered Today,UPI Loads Remaining Today" s-column="year" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;year&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"year")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td align="center">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Client,month,year,MTD Load Count,MTD Tons,UPI Loads Delivered Today,UPI Loads Remaining Today" s-column="MTD Load Count" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;MTD Load Count&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"MTD Load Count")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td align="center">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Client,month,year,MTD Load Count,MTD Tons,UPI Loads Delivered Today,UPI Loads Remaining Today" s-column="MTD Tons" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;MTD Tons&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"MTD Tons")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td align="center">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Client,month,year,MTD Load Count,MTD Tons,UPI Loads Delivered Today,UPI Loads Remaining Today" s-column="UPI Loads Delivered Today" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;UPI Loads Delivered Today&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"UPI Loads Delivered Today")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
			<td align="center">
			<!--webbot bot="DatabaseResultColumn" s-columnnames="Client,month,year,MTD Load Count,MTD Tons,UPI Loads Delivered Today,UPI Loads Remaining Today" s-column="UPI Loads Remaining Today" b-tableformat="TRUE" b-hashtml="FALSE" b-makelink="FALSE" clientside b-MenuFormat preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;UPI Loads Remaining Today&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" startspan --><%=FP_FieldVal(fp_rs,"UPI Loads Remaining Today")%><!--webbot bot="DatabaseResultColumn" endspan --></td>
		</tr>
		<!--webbot bot="DatabaseRegionEnd" b-tableformat="TRUE" b-menuformat="FALSE" u-dbrgn2="_fpclass/fpdbrgn2.inc" i-groupsize="0" clientside tag="TBODY" preview="&lt;tr&gt;&lt;td colspan=&quot;64&quot; bgcolor=&quot;#FFFF00&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;" startspan --><!--#include file="_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan --></tbody>
</table>
</BODY>
</HTML>