//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Dashboard_DashboardKpiThroughputDwellAndRevenue {
    
    /// <summary>
    /// GaugeContainer1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dundas.Gauges.WebControl.GaugeContainer GaugeContainer1;
    
    /// <summary>
    /// PlannedRevenuePerMinuteToday control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.SqlDataSource PlannedRevenuePerMinuteToday;
    
    /// <summary>
    /// ThroughputToday control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.SqlDataSource ThroughputToday;
    
    /// <summary>
    /// Chart1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dundas.Charting.WebControl.Chart Chart1;
    
    /// <summary>
    /// ThroughputHistory control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.SqlDataSource ThroughputHistory;
    
    /// <summary>
    /// GaugeContainer2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dundas.Gauges.WebControl.GaugeContainer GaugeContainer2;
    
    /// <summary>
    /// BudwayDwellToday control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.SqlDataSource BudwayDwellToday;
    
    /// <summary>
    /// Chart2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dundas.Charting.WebControl.Chart Chart2;
    
    /// <summary>
    /// BudwayDwellHistory control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.SqlDataSource BudwayDwellHistory;
    
    /// <summary>
    /// GaugeContainer3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dundas.Gauges.WebControl.GaugeContainer GaugeContainer3;
    
    /// <summary>
    /// RevenuePerLoadMonthToDate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.SqlDataSource RevenuePerLoadMonthToDate;
    
    /// <summary>
    /// GaugeContainer4 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dundas.Gauges.WebControl.GaugeContainer GaugeContainer4;
    
    /// <summary>
    /// RevenuePerLoadTrailingYear control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.SqlDataSource RevenuePerLoadTrailingYear;
    
    /// <summary>
    /// GaugeContainer5 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dundas.Gauges.WebControl.GaugeContainer GaugeContainer5;
    
    /// <summary>
    /// RevenuePerMinuteMonthToDate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.SqlDataSource RevenuePerMinuteMonthToDate;
    
    /// <summary>
    /// GaugeContainer6 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Dundas.Gauges.WebControl.GaugeContainer GaugeContainer6;
    
    /// <summary>
    /// RevenuePerMinuteTrailingYear control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.SqlDataSource RevenuePerMinuteTrailingYear;
}
