namespace BopsDataAccess
{
    public class BopsRfsStakeholderClientMappingDetail
    {
        private int _MappingRef;
        private int _RoleRef;
        private int _SourceClientRef;

        public int MappingRef
        {
            get { return _MappingRef; }
            set { _MappingRef = value; }
        }

        public int RoleRef
        {
            get { return _RoleRef; }
            set { _RoleRef = value; }
        }

        public int SourceClientRef
        {
            get { return _SourceClientRef; }
            set { _SourceClientRef = value; }
        }

        // Equals and GetHashCode generated by default by Resharper.

        public override bool Equals(object obj)
        {
            if (this == obj) return true;
            BopsRfsStakeholderClientMappingDetail that = obj as BopsRfsStakeholderClientMappingDetail;
            if (that == null) return false;
            if (_MappingRef != that._MappingRef) return false;
            if (_RoleRef != that._RoleRef) return false;
            if (_SourceClientRef != that._SourceClientRef) return false;
            return true;
        }

        public override int GetHashCode()
        {
            int result = _MappingRef;
            result = 29 * result + _RoleRef;
            result = 29 * result + _SourceClientRef;
            return result;
        }
    }
}
